// This file is auto-generated by the Caffeine build system.
// It provides the actor creation utilities for the backend canister.

import { Actor, type ActorConfig, HttpAgent, type Identity } from "@dfinity/agent";
import { IDL } from "@dfinity/candid";
import type { _SERVICE } from "./backend.d";

export type backendInterface = _SERVICE;

export interface CreateActorOptions {
  agentOptions?: {
    host?: string;
    identity?: Identity;
    fetchRootKey?: boolean;
  };
  actorOptions?: ActorConfig;
  agent?: HttpAgent;
  processError?: (e: unknown) => never;
}

export class ExternalBlob {
  private bytes: Uint8Array | null = null;
  private url: string | null = null;
  public onProgress?: (percentage: number) => void;

  private constructor() {}

  static fromURL(url: string): ExternalBlob {
    const blob = new ExternalBlob();
    blob.url = url;
    return blob;
  }

  static fromBytes(bytes: Uint8Array): ExternalBlob {
    const blob = new ExternalBlob();
    blob.bytes = bytes;
    return blob;
  }

  async getBytes(): Promise<Uint8Array> {
    if (this.bytes) return this.bytes;
    if (this.url) {
      const response = await fetch(this.url);
      const buffer = await response.arrayBuffer();
      this.bytes = new Uint8Array(buffer);
      return this.bytes;
    }
    throw new Error("ExternalBlob has no data source");
  }

  getURL(): string | null {
    return this.url;
  }
}

// IDL factory for the backend canister
const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    admin: IDL.Null,
    guest: IDL.Null,
    user: IDL.Null,
  });

  const Movie = IDL.Record({
    id: IDL.Nat,
    title: IDL.Text,
    description: IDL.Text,
    genre: IDL.Text,
    duration: IDL.Nat,
    rating: IDL.Text,
    posterUrl: IDL.Text,
    isActive: IDL.Bool,
  });

  const Showtime = IDL.Record({
    id: IDL.Nat,
    movieId: IDL.Nat,
    date: IDL.Text,
    time: IDL.Text,
    hall: IDL.Text,
    totalSeats: IDL.Nat,
    price: IDL.Nat,
  });

  const Booking = IDL.Record({
    id: IDL.Nat,
    userId: IDL.Principal,
    showtimeId: IDL.Nat,
    movieId: IDL.Nat,
    seats: IDL.Vec(IDL.Text),
    totalPrice: IDL.Nat,
    bookingDate: IDL.Text,
    status: IDL.Text,
  });

  return IDL.Service({
    _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
    addMovie: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    addShowtime: IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
    cancelBooking: IDL.Func([IDL.Nat], [IDL.Bool], []),
    createBooking: IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    deleteMovie: IDL.Func([IDL.Nat], [IDL.Bool], []),
    deleteShowtime: IDL.Func([IDL.Nat], [IDL.Bool], []),
    getAdminStats: IDL.Func([], [IDL.Nat, IDL.Nat], ["query"]),
    getAllBookings: IDL.Func([], [IDL.Vec(Booking)], ["query"]),
    getAllShowtimes: IDL.Func([], [IDL.Vec(Showtime)], ["query"]),
    getBookedSeats: IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ["query"]),
    getCallerUserRole: IDL.Func([], [UserRole], ["query"]),
    getMovie: IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ["query"]),
    getMovies: IDL.Func([], [IDL.Vec(Movie)], ["query"]),
    getMyBookings: IDL.Func([], [IDL.Vec(Booking)], []),
    getShowtimes: IDL.Func([IDL.Nat], [IDL.Vec(Showtime)], ["query"]),
    isCallerAdmin: IDL.Func([], [IDL.Bool], ["query"]),
    updateMovie: IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool], [IDL.Bool], []),
  });
};

export function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (bytes: Uint8Array) => Promise<ExternalBlob>,
  options?: CreateActorOptions,
): Promise<backendInterface> {
  const agent = options?.agent ?? new HttpAgent({
    ...options?.agentOptions,
  });

  const actor = Actor.createActor<backendInterface>(idlFactory, {
    agent,
    canisterId,
    ...options?.actorOptions,
  });

  return Promise.resolve(actor);
}
